// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/server_test.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingInput struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingInput) Reset()         { *m = PingInput{} }
func (m *PingInput) String() string { return proto.CompactTextString(m) }
func (*PingInput) ProtoMessage()    {}
func (*PingInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f59c0184cc73450b, []int{0}
}

func (m *PingInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingInput.Unmarshal(m, b)
}
func (m *PingInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingInput.Marshal(b, m, deterministic)
}
func (m *PingInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingInput.Merge(m, src)
}
func (m *PingInput) XXX_Size() int {
	return xxx_messageInfo_PingInput.Size(m)
}
func (m *PingInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PingInput.DiscardUnknown(m)
}

var xxx_messageInfo_PingInput proto.InternalMessageInfo

func (m *PingInput) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type PingOutput struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingOutput) Reset()         { *m = PingOutput{} }
func (m *PingOutput) String() string { return proto.CompactTextString(m) }
func (*PingOutput) ProtoMessage()    {}
func (*PingOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f59c0184cc73450b, []int{1}
}

func (m *PingOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingOutput.Unmarshal(m, b)
}
func (m *PingOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingOutput.Marshal(b, m, deterministic)
}
func (m *PingOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingOutput.Merge(m, src)
}
func (m *PingOutput) XXX_Size() int {
	return xxx_messageInfo_PingOutput.Size(m)
}
func (m *PingOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PingOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PingOutput proto.InternalMessageInfo

func (m *PingOutput) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*PingInput)(nil), "grpc.PingInput")
	proto.RegisterType((*PingOutput)(nil), "grpc.PingOutput")
}

func init() { proto.RegisterFile("grpc/server_test.proto", fileDescriptor_f59c0184cc73450b) }

var fileDescriptor_f59c0184cc73450b = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x8a, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x2b, 0xa9, 0x73, 0x71, 0x06, 0x64, 0xe6, 0xa5, 0x7b, 0xe6,
	0x15, 0x94, 0x96, 0x08, 0x49, 0x71, 0x71, 0xa4, 0x17, 0xa5, 0xa6, 0x96, 0x64, 0xe6, 0xa5, 0x4b,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x4a, 0x1a, 0x5c, 0x5c, 0x20, 0x85, 0xfe, 0xa5,
	0x25, 0x04, 0x54, 0x1a, 0x19, 0x72, 0xb1, 0x84, 0xa4, 0x16, 0x97, 0x08, 0x69, 0x72, 0xb1, 0x80,
	0x74, 0x08, 0xf1, 0xeb, 0x81, 0x6c, 0xd2, 0x83, 0x5b, 0x23, 0x25, 0x80, 0x10, 0x80, 0x18, 0x97,
	0xc4, 0x06, 0x76, 0x92, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x36, 0x2f, 0x29, 0x3c, 0xac, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	Ping(ctx context.Context, in *PingInput, opts ...grpc.CallOption) (*PingOutput, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Ping(ctx context.Context, in *PingInput, opts ...grpc.CallOption) (*PingOutput, error) {
	out := new(PingOutput)
	err := c.cc.Invoke(ctx, "/grpc.Test/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	Ping(context.Context, *PingInput) (*PingOutput, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Test/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Ping(ctx, req.(*PingInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Test_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/server_test.proto",
}
