// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primitive/primitive.proto

package primitivev1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ISOTime use as Date field.
type ISOTime struct {
	V                    string   `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ISOTime) Reset()         { *m = ISOTime{} }
func (m *ISOTime) String() string { return proto.CompactTextString(m) }
func (*ISOTime) ProtoMessage()    {}
func (*ISOTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7ecb99062b6ed19, []int{0}
}

func (m *ISOTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ISOTime.Unmarshal(m, b)
}
func (m *ISOTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ISOTime.Marshal(b, m, deterministic)
}
func (m *ISOTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ISOTime.Merge(m, src)
}
func (m *ISOTime) XXX_Size() int {
	return xxx_messageInfo_ISOTime.Size(m)
}
func (m *ISOTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ISOTime.DiscardUnknown(m)
}

var xxx_messageInfo_ISOTime proto.InternalMessageInfo

func (m *ISOTime) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *ISOTime) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

// String use as string which able to set to null value.
type String struct {
	V                    string   `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7ecb99062b6ed19, []int{1}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *String) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

// Int use as int64 which able to set to null value.
type Int struct {
	V                    int64    `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int) Reset()         { *m = Int{} }
func (m *Int) String() string { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()    {}
func (*Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7ecb99062b6ed19, []int{2}
}

func (m *Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int.Unmarshal(m, b)
}
func (m *Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int.Marshal(b, m, deterministic)
}
func (m *Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int.Merge(m, src)
}
func (m *Int) XXX_Size() int {
	return xxx_messageInfo_Int.Size(m)
}
func (m *Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Int proto.InternalMessageInfo

func (m *Int) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *Int) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

// Double use as float which able to set to null value.
type Double struct {
	V                    float64  `protobuf:"fixed64,1,opt,name=v,proto3" json:"v,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Double) Reset()         { *m = Double{} }
func (m *Double) String() string { return proto.CompactTextString(m) }
func (*Double) ProtoMessage()    {}
func (*Double) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7ecb99062b6ed19, []int{3}
}

func (m *Double) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Double.Unmarshal(m, b)
}
func (m *Double) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Double.Marshal(b, m, deterministic)
}
func (m *Double) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Double.Merge(m, src)
}
func (m *Double) XXX_Size() int {
	return xxx_messageInfo_Double.Size(m)
}
func (m *Double) XXX_DiscardUnknown() {
	xxx_messageInfo_Double.DiscardUnknown(m)
}

var xxx_messageInfo_Double proto.InternalMessageInfo

func (m *Double) GetV() float64 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *Double) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

// Boolean use as boolean value which nullable.
type Boolean struct {
	V                    bool     `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7ecb99062b6ed19, []int{4}
}

func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (m *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(m, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetV() bool {
	if m != nil {
		return m.V
	}
	return false
}

func (m *Boolean) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

func init() {
	proto.RegisterType((*ISOTime)(nil), "foundation.primitive.v1.ISOTime")
	proto.RegisterType((*String)(nil), "foundation.primitive.v1.String")
	proto.RegisterType((*Int)(nil), "foundation.primitive.v1.Int")
	proto.RegisterType((*Double)(nil), "foundation.primitive.v1.Double")
	proto.RegisterType((*Boolean)(nil), "foundation.primitive.v1.Boolean")
}

func init() { proto.RegisterFile("primitive/primitive.proto", fileDescriptor_c7ecb99062b6ed19) }

var fileDescriptor_c7ecb99062b6ed19 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0xcc,
	0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0xd5, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4,
	0xd3, 0xf2, 0x4b, 0xf3, 0x52, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0xf4, 0x10, 0x72, 0x65, 0x86, 0x4a,
	0x06, 0x5c, 0xec, 0x9e, 0xc1, 0xfe, 0x21, 0x99, 0xb9, 0xa9, 0x42, 0x3c, 0x5c, 0x8c, 0x65, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x8c, 0x65, 0x42, 0xe2, 0x5c, 0xec, 0x99, 0xc5, 0xf1, 0x79,
	0xa5, 0x39, 0x39, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x6c, 0x99, 0xc5, 0x7e, 0xa5, 0x39,
	0x39, 0x4a, 0xfa, 0x5c, 0x6c, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0xc4, 0x6a, 0xd0, 0xe1, 0x62,
	0xf6, 0xcc, 0x2b, 0x41, 0xa8, 0x66, 0x26, 0x64, 0xbc, 0x4b, 0x7e, 0x69, 0x52, 0x0e, 0x92, 0x7b,
	0x18, 0xf1, 0x6a, 0x30, 0xe0, 0x62, 0x77, 0xca, 0xcf, 0xcf, 0x49, 0x4d, 0xcc, 0x43, 0xe8, 0xe0,
	0xc0, 0xa7, 0xc3, 0xa9, 0x8c, 0x4b, 0x3a, 0x39, 0x3f, 0x57, 0x0f, 0x47, 0x90, 0x38, 0xf1, 0x05,
	0xc0, 0x78, 0x01, 0xa0, 0xb0, 0x0b, 0x60, 0x8c, 0xe2, 0x86, 0xcb, 0x97, 0x19, 0x2e, 0x62, 0x62,
	0x76, 0x0b, 0x88, 0x58, 0xc5, 0x24, 0xee, 0x86, 0xd0, 0x0e, 0xd7, 0xa0, 0x17, 0x66, 0x78, 0x0a,
	0x59, 0x26, 0x06, 0x2e, 0x13, 0x13, 0x66, 0x98, 0xc4, 0x06, 0x8e, 0x0b, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0x86, 0x2b, 0x2f, 0xa8, 0x01, 0x00, 0x00,
}
